simplesocial/groups/urls.py
from django import urls
from django.urls import path
from groups.views import CreateGroup, GroupsList, GroupDetail, JoinGroup, LeaveGroup, UserGroupList, CreateGroupPost

app_name = 'groups'

urlpatterns = [
    path('',GroupsList.as_view(),name='all'),
    path('new',CreateGroup.as_view(),name='create'),
    path('posts_in/<pk>',GroupDetail.as_view(),name='single'),
    path('join/<pk>',JoinGroup.as_view(),name='join'),
    path('leave/<pk>',LeaveGroup.as_view(),name="leave"),
    path('for/<username>',UserGroupList.as_view(),name='for_user'),
    path('post_to/<pk>', CreateGroupPost.as_view() , name="group_post")
]

simplesocial/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('signup',views.SignUp.as_view(),name="signup"),
]

simplesocial/posts/urls.py
from operator import imod
from django import urls
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [ 
    path('', views.PostList.as_view(),name="all"),
    path('new/', views.createPost.as_view(),name="create"),
    path('by/<username>', views.UserPosts.as_view(),name="for_user"),
    path('by/<username>/<pk>', views.PostDetail.as_view(),name="detail"),
    path('delete/<pk>', views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name="index"),
    path('social/', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name="accounts"),
    path('posts/', include("posts.urls")),
    path('groups/', include("groups.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/groups/models.py
from django.db import models

from django.conf import settings
from django.urls import reverse

# Create your models here.

# https://docs.djangoproject.com/en/4.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag

class Group(models.Model):

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField()

    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='GroupMembers')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'id':self.id})


class GroupMembers(models.Model):

    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.group.name

    class Meta:
        unique_together = ('group','user')

simplesocial/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):

    def __str__(self):
        return "@{}".format(self.username)

simplesocial/posts/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings

from groups.models import Group, GroupMembers

# Create your models here.

class Post(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.message
    
    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.Username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']

simplesocial/main/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

simplesocial/groups/views.py
from django.db import IntegrityError
from django.contrib import messages

from django import views
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from groups.models import Group, GroupMembers
from django.urls import reverse, reverse_lazy

from main.owner import OwnerListView, OwnerDetailView

from django.shortcuts import redirect

from posts.models import Post

# Create your views here.

class CreateGroup(LoginRequiredMixin, CreateView):
    model = Group
    fields = ['name' , 'description']
    success_url = reverse_lazy("groups:all")

    def form_valid(self, form):
        group = form.save()
        user = self.request.user
        GroupMembers.objects.create(group=group, user=user)
        return super().form_valid(form)

class GroupsList(ListView):
    model = Group

class GroupDetail(OwnerDetailView):
    model = Group

class JoinGroup(LoginRequiredMixin, views.View):
    
    def get(self, request, pk):
        group = Group.objects.get(pk=pk)
        try:
            GroupMembers.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,("You are already a member of this group{}".format(group.name)))

        return redirect(reverse_lazy('groups:single', args=[pk]))

class LeaveGroup(LoginRequiredMixin, views.View):

    def get(self, request, pk):
        group = Group.objects.get(pk=pk)
        group_member = GroupMembers.objects.get(group=group,user=self.request.user)
        try:
            group_member.delete()
        
        except:
            messages.warning(self.request,("Unable to leave from group{}".format(group.name)))
        
        return redirect(reverse_lazy('groups:single', args=[pk]))

class UserGroupList(OwnerListView):

    model = GroupMembers
    template_name = 'groups/user_group_list.html'

class CreateGroupPost(CreateView):
    
    model = Post
    template_name= 'posts/post_form.html'
    fields=['message', 'img']
    
    def get_success_url(self):
        return reverse_lazy('groups:single', args=[self.kwargs['pk']])

    def form_valid(self, form):
        object = form.save(commit=False)
        object.group = Group.objects.get(pk=self.kwargs['pk'])
        object.user = self.request.user
        object.save
        return super(CreateGroupPost, self).form_valid(form)

simplesocial/main/views.py
from django.views.generic import ListView, CreateView
from .forms import UserCreateForm
from django.urls import reverse_lazy

# Create your views here.

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'main/signup.html'

simplesocial/posts/views.py
from . import models
from main.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerDeleteView
from django.views.generic import ListView
from django.urls import reverse_lazy

from django.conf import settings


class PostList(ListView):
    model = models.Post

class UserPosts(OwnerListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

class PostDetail(OwnerDetailView):
    model = models.Post

class createPost(OwnerCreateView):
    model = models.Post
    user = settings.AUTH_USER_MODEL
    fields = ['message', 'img']

    def get_success_url(self):
        return reverse_lazy("posts:for_user",args=(self.request.user.username,))

class DeletePost(OwnerDeleteView):
    model = models.Post
    def get_success_url(self):
        return reverse_lazy("posts:for_user",args=(self.request.user.username,))

simplesocial/simplesocial/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "index.html"

simplesocial/groups/templates/groups/_group.html
<div class="card" >
<div class="card-body">
<a href="{% url 'groups:single' pk=group.pk %}"><h3>{{ group.name }}</h3></a>
<h4>{{group.description}}</h4>
<small>{{ group.members.count }} member{{ group.members.count|pluralize }}</small>
<small>{{ group.posts.count }} post{{ group.posts.count|pluralize }}</small>
</div>
</div>

simplesocial/groups/templates/groups/group_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
<div class="row">
    <div class="col-md-4">
        <div class="content">
        {% include 'groups/_group.html' %}
        <br><br>

        {% if user in group.members.all %}
        <a href="{% url 'groups:group_post' pk=group.pk %}" class="btn btn-primary btn-md">Post to this group</a>
        <br><br>
        <a href="{% url 'groups:leave' pk=group.pk %}" class="btn btn-large btn-warning">Leave</a>

        {% else %}
        <h4>Join to post in this group</h4>
        <a href="{% url 'groups:join' pk=group.pk %}" class="btn btn-large btn-success">Join</a>
    
        {% endif %}
        </div>
    </div>
    
<div class="col-md-6">
    <div class="content">
        {% if group.posts.count == 0 %}
            <h3>No posts in this group</h3>
        {% else %}
            <table class="table">
                <tbody>
                    {% for post in group.posts.all %}
                        {% include 'posts/_post.html' %}
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</div>
</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class = 'btn btn-primary btn-lg' value="Create">
    </form>

{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-md-4">
		<div class="content">
			{% if user.is_authenticated %}
			<h2>
				Hola
				<a style="text-decoration:none ;" href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>!
			</h2>
	
		{% endif %}
	
				<h3>Welcome to the Groups Page!</h3>
		</div>
		{% if user.is_authenticated %}
		<a href="{% url 'groups:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create New Group!</a>
		{% endif %}
	</div>
	<div class="col-md-6" style="overflow: auto; width:50em; height: 40em;">
		{% if group_list %}
		<table class="table">
			<tbody>
				{% for group in group_list %}
					<tr>
						<td>
							{% include 'groups/_group.html' %}
						</td>
					</tr>

				{% endfor %}
			</tbody>

		</table>
		{% else %}
			{% if user.is_authenticated %}
				<h3>No group to list, please create a group to post</h3>
			{% else %}
				<h3>No group to list, please login to create group</h3>
			{% endif %}
		{% endif %}
		
	</div>
</div>

{% endblock %}

simplesocial/groups/templates/groups/user_group_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-md-4">
		<div class="content">
			{% if user.is_authenticated %}
			<h2>
				Hola
				<a style="text-decoration:none ;" href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>!
			</h2>
	
		{% endif %}
	
		</div>
        <a href="{% url 'groups:all' %}" class="btn btn-primary btn-sm">View All Groups</a> <br><br>
		{% if user.is_authenticated %}
		<a href="{% url 'groups:create' %}" class="btn btn-warning" role="button">Create New Group!</a>
    </div>
    <div class="col-md-6" style="overflow: auto; width:50em; height: 40em;">
        {% if groupmembers_list %}
        <table class="table">
            <tbody>
                {% for groupmember in groupmembers_list %}
                    <tr>
                        <td>
                            {% with group=groupmember.group %}
                            {% include 'groups/_group.html' %}
                            {% endwith %}
                        </td>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h3>You have not joined any group.</h3>
        <h4>Please join to post in the group</h4>
        {% endif %}
        
    </div>

        
        {% endif %}
	
{% endblock %}

simplesocial/main/templates/main/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary"> Submit </button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

simplesocial/posts/templates/posts/_post.html
<tr>
    <td>
        <div class="card" >
            <div class="card-body">
                <strong>{{post.user.username}}</strong>
                {% if post.group is not None %}
                to <strong>{{post.group}}</strong>
                {% endif %}
                </br>
                <strong>{{post.created_at}}</strong>
                <br><br><p>{{post.message}}
                {% if post.user == user %}
                <a text-decoration="none" href="{% url 'posts:delete' post.pk %}">Delete</a>
                {% endif %}
                </p>
            </div>
            {% if post.img %}
            <img class="card-img-bottom" src="{{post.img.url}}" alt="image not found" width="50%" height="50%"></br></br>
            {% endif %}

        </div>

    </td>
</tr>

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap5 %}
<form method="POST">
	{% csrf_token %}
	{{post.user.username}}
	{% if post.group is not None %}
	to <strong>{{post.group}}</strong>
	{% endif %}
	</br>
	<strong>{{post.created_at}}</strong>
	<h3>{{post.message}}</h3></br>
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:for_user' username=user.username %}" class="btn btn-light btn-large">Cancel</a>
</form>
{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% include "posts/_post.html" %}

simplesocial/posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap5 %}
<h4>Create a new post</h4>
<form action="" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary btn-lg">
</form>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
<h1>Post list</h1>

simplesocial/posts/templates/posts/user_post_list.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap5 %}

<div class="container-fluid">
<div class="row">
<div class="col-md-4">
    <h2>Post history of
    <a style="text-decoration:none ;" href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a></h2>
    <br><br>
    <a href="{% url 'posts:create' %}" class="btn btn-success" role="button"><span class="fa fa-plus"></span> New Post</a>

</div>

<div class="col-md-6" style="overflow: auto; width:50em; height: 40em;">

    {% if post_list %}
        <table class="table">
            <tbody>
                {% for post in post_list %}
                    {% include 'posts/_post.html' %}
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>You have not posted anything</h2>
        <h4>Click <strong>New Post </strong>to share whats on your mind</h4>
    {% endif %}

</div>
</div>
</div>
{% endblock %}

simplesocial/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">Home</a>
          <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">

          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'posts:for_user' username=user.username %}">My Posts</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:for_user' username=user.username %}">My Groups</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:create'  %}">Create Group</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>

        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'main:signup' %}">Sign Up</a></li>

        {% endif %}
          </div>
          </ul>
        </div>
      </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to Star Social</h1>
<a href="{% url 'main:signup' %}">Sign Up</a>
{% endblock %}